require("plugins-setup")
require("core.options")
require("core.keymaps")
require("core.config")
require("plugins.comment")
require("plugins.nvim-tree")
require("plugins.lualine")
require("plugins.nvim-cmp")
require("plugins.autopairs")
-- require("plugins.treesitter")
require("plugins.gitsigns")
require("plugins.harpoon")
